# Generated by Django 5.1.1 on 2024-11-16 16:21

import django.db.models.deletion
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brand_image_name_alter_groupproduct_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='brand image'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='group_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent_of_product', to='product.groupproduct', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='image of group'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='image of product'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='images'),
        ),
    ]
